### ISSUE TITLE
PermissionError on Windows Accdb/Mdb/SQL Unit tests using Python 3.6

### ISSUE THREAD

**Issue by snelson3** [ticdat/ticdat#1]
_From @snelson3 on June 23, 2017 19:32_

When running the accdb/mdb/sql unit tests on Python 3.6 on Windows, they all generate a PermissionError in tearDownClass class and in TestSilly.

Example of the TearDownClass error:

```
======================================================================
ERROR: tearDownClass (__main__.TestAccdb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ticdev\Anaconda2\envs\py3\Lib\site-packages\ticdat\testing\testaccdb.py", line 21, in tearDownClass
    shutil.rmtree(_scratchDir)
  File "C:\Users\ticdev\Anaconda2\envs\py3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\ticdev\Anaconda2\envs\py3\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\ticdev\Anaconda2\envs\py3\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'TestAccdb_scratch\\weirdDiet.accdb'

----------------------------------------------------------------------

```

Example of the TestSilly error:
```
======================================================================
ERROR: testSilly (__main__.TestSql)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testsql.py", line 288, in testSilly
    tdf.sql.write_db_data(ticDat, makeCleanPath(filePath))
  File "C:\Users\ticdev\Anaconda2\envs\py3\lib\site-packages\ticdat\testing\ticdattestutils.py", line 178, in makeCleanPath
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'TestSql_scratch\\silly.db'
```

_Copied from original issue: opalytics/opalytics-ticdat#153_

**Comment by pjcpjc** [comment]
SQLite tests work on MacOSX. @sean-opex - can you ty this unit tests on your machine?
