### ISSUE TITLE
Dependency Handling 

### ISSUE THREAD

**Issue by mohit-mhjn** [ticdat/ticdat#53]
@pjcpjc  

Disclaimer:: A user of anaconda may not see the following, but someone who isn't using anaconda for package management would certainly encounter this situation.

This is regarding the newer version of ticdat (the one on the `develop` branch), 
I installed it for havasu on an azure vm (spark cluster), where it requires following dependencies to be installed (i encountered `ModuleNotFound Exception` with `import ticdat` statement) 

`xlrd`,`opexpyxl`,`pyscopg2-binary`

I saw that all imports are within a trial and exception handler but I still see a problem. Didn't dig deep into this. my first question is that : Is this exception expected? 
 
If not then, 
1. Are these dependencies for the short term? In the long term, they would go off?
2. If not, Can you handle these with  `install requires`

**Comment by pjcpjc** [comment]
I don't think `install_requires` is needed because they are not minimally required.

Don't you see messages like `"xlrd needs to be installed to use this subroutine"` . If not, can you share the stack trace?

**Comment by mohit-mhjn** [comment]
Okay so I uninstalled xlrd and it shows the following msg when ticdat tries to create a pandat object.
```
PS C:\Users\Admin\Desktop\opex_files\havasu> python -O .\run_havasu.py -i .\test_havasu\input_dataset\very_small_1PMD_1T.xlsx -o report.xlsx

      __
     / /  ___  __  _____ ____ __ __
    / _ \/ _ `/ |/ / _ `(_-</ // /
   /_//_/\_,_/|___/\_,_/___/\_,_/

   Enumeration and Set-Covering based transportation problem solver

   version :: 0.1.1
   copyrights@2020 | Opex Analytics LLC - A Llamasoft Company

input file .\test_havasu\input_dataset\very_small_1PMD_1T.xlsx : output file report.xlsx
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\pandatio.py", line 480, in _get_sheet_names
    xl = pd.ExcelFile(xls_file_path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\excel\_base.py", line 819, in __init__
    self._reader = self._engines[engine](self._io)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\excel\_xlrd.py", line 20, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\compat\_optional.py", line 99, in import_optional_dependency
    version = _get_version(module)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\compat\_optional.py", line 48, in _get_version
    raise ImportError("Can't determine version for {}".format(module.__name__))
ImportError: Can't determine version for xlrd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\run_havasu.py", line 19, in <module>
    hm.main()
  File "C:\Users\Admin\Desktop\opex_files\havasu\havasu\__main__.py", line 57, in main
    standard_main(input_schema, solution_schema, _solve)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 168, in standard_main
    return _standard_main_pandat(input_schema, solution_schema, solve)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 209, in _standard_main_pandat
    dat = input_schema.xls.create_pan_dat(input_file)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\pandatio.py", line 462, in create_pan_dat
    for t, s in self._get_sheet_names(xls_file_path).items():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\pandatio.py", line 482, in _get_sheet_names
    raise TicDatError("Unable to open %s as xls file : %s"%(xls_file_path, e))
ticdat.utils.TicDatError: Unable to open .\test_havasu\input_dataset\very_small_1PMD_1T.xlsx as xls file : Can't determine version for xlrd
```

**Comment by mohit-mhjn** [comment]
looks like it's an optional depedency in pandas, because a lot of times the pandas users won't deal with excel files. Similarly it goes with openpyxl 
```
TICDAT Overwriting output file report.xlsx
Traceback (most recent call last):
  File ".\run_havasu.py", line 19, in <module>
    hm.main()
  File "C:\Users\Admin\Desktop\opex_files\havasu\havasu\__main__.py", line 57, in main
    standard_main(input_schema, solution_schema, _solve)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 168, in standard_main
    return _standard_main_pandat(input_schema, solution_schema, solve)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\utils.py", line 222, in _standard_main_pandat
    solution_schema.xls.write_file(sln, output_file, case_space_sheet_names=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ticdat\pandatio.py", line 514, in write_file
    writer = pd.ExcelWriter(file_path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\excel\_openpyxl.py", line 19, in __init__
    from openpyxl.workbook import Workbook
ImportError: cannot import name 'Workbook' from 'openpyxl.workbook' (unknown location) ```

**Comment by pjcpjc** [comment]
Looks like more of a `pandas` thing. The general rule I look for is a clean `import ticdat` and then a good error message if you try to do something that needs an additional package. (I was told by a few people they'd prefer `ticdat` this way from a few years ago, so its not overly pushy with installing other packages).
