### ISSUE TITLE
ticdat overly agressive in assuming a pandas installation for non-pandas work

### ISSUE THREAD

**Issue by spkelle2** [ticdat/ticdat#61]
Totally nitpicky, but wanted to bring to your attention nonetheless for the sake of having bombproof example code. If pandas is not installed when running `examples/gurobipy/diet/diet.py` the module fails with a fairly ambiguous failure code. A little digging and I figured it out, but new users may like to have that heads up. Here's the traceback. I'll open a PR this afternoon.

```
Traceback (most recent call last):
  File "diet.py", line 113, in <module>
    standard_main(input_schema, solution_schema, solve)
  File "C:\Users\seanp\miniconda\lib\site-packages\ticdat\utils.py", line 170, in standard_main
    return _standard_main_ticdat(input_schema, solution_schema, solve)
  File "C:\Users\seanp\miniconda\lib\site-packages\ticdat\utils.py", line 330, in _standard_main_ticdat
    sln = solve(dat)
  File "diet.py", line 75, in solve
    assert not input_schema.find_data_type_failures(dat)
  File "C:\Users\seanp\miniconda\lib\site-packages\ticdat\ticdatfactory.py", line 1529, in find_data_type_failures
    if not data_type.valid_data(full_row[field]) :
  File "C:\Users\seanp\miniconda\lib\site-packages\ticdat\utils.py", line 61, in valid_data
    if pd.isnull(data):
AttributeError: 'NoneType' object has no attribute 'isnull'
```

**Comment by pjcpjc** [comment]
Reasonable request. Fixed in commit 2c28bd8. Let me know if you need a beta release for this.
